#!/usr/bin/env bash

if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

FILE_PATH="$1"
SERVER_IP="184.72.114.154"
USERNAME="ubuntu"
SSH_KEY_PATH="$4"

scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/

if [ "$?" -eq 0 ]; then
    echo "File successfully transferred to $USERNAME@$SERVER_IP:~/"
else
    echo "File transfer failed."
    exit 1
fi

