#!/usr/bin/env bash
# Install nginx on server, listening on port 80 (default),
# and return a page that contains the expected output string

sudo apt-get -y update
sudo apt-get -y install nginx

ufw allow 80  # port listening on

mkdir -p /var/www/html
# reassign ownership to user acct
sudo chown -R "$USER":"$USER" /var/www/html
echo "Holberton School" | sudo tee /var/www/html/index.html
sudo service nginx start
